import { slug } from '../../lib/store.js';

// Parse "name, type, label" lines into an input schema.
export function parseInputs(text) {
  return String(text || '')
    .split('\n')
    .map((l) => l.trim())
    .filter(Boolean)
    .map((l) => {
      const [name, type, ...rest] = l.split(',').map((s) => s.trim());
      return { name, type: type || 'string', label: rest.join(', ') || name };
    })
    .filter((f) => f.name);
}

// Generate an executable, code-first skill module. The run body is user code
// that receives (input, ctx) and returns a value.
export function skillModuleSource({ id, name, description, version, inputs, runBody, tests }) {
  const def = {
    id: slug(id || name),
    name,
    description: description || '',
    version: version || '1.0.0',
    inputs,
  };
  return `// Generated by Claude Engine · Skill Builder. Safe to edit by hand.
export const definition = ${JSON.stringify(def, null, 2)};

/** Repeatable functionality as code. @param {object} input @param {{provider}} ctx */
export async function run(input, ctx) {
${indent(runBody || 'return { ok: true };')}
}

export const tests = ${JSON.stringify(tests || [], null, 2)};
`;
}

const indent = (s) => String(s).split('\n').map((l) => '  ' + l).join('\n');
