import { slug } from '../../lib/store.js';

// Generate a code-first agent module. The agent composes skills (run via
// ctx.skills.run) and calls the LLM provider (ctx.provider.complete).
export function agentModuleSource({ id, name, description, model, systemPrompt, skills, taskLabel }) {
  const def = {
    id: slug(id || name),
    name,
    description: description || '',
    model: model || 'claude-opus-4-8',
    systemPrompt: systemPrompt || '',
    skills: skills || [],
    inputs: [{ name: 'task', type: 'text', label: taskLabel || 'Task' }],
  };
  return `// Generated by Claude Engine · Agent Composer. Safe to edit by hand.
export const definition = ${JSON.stringify(def, null, 2)};

/**
 * Run the agent. ctx = { provider, skills: { run(id, input) } }.
 * Default composition: run each skill on the task, then ask the LLM.
 */
export async function run(input, ctx) {
  const task = String(input.task || "");
  const skillOutputs = {};
  for (const id of definition.skills) {
    try {
      skillOutputs[id] = await ctx.skills.run(id, { text: task, task });
    } catch (err) {
      skillOutputs[id] = { error: err.message };
    }
  }
  const prompt = [
    task,
    Object.keys(skillOutputs).length ? "Skill outputs: " + JSON.stringify(skillOutputs) : "",
  ].filter(Boolean).join("\\n\\n");
  const reply = await ctx.provider.complete({
    system: definition.systemPrompt,
    prompt,
    model: definition.model,
  });
  return { reply: reply.text, model: reply.model, provider: reply.provider, skillOutputs, usage: reply.usage };
}
`;
}
